### PR TITLE
Fix - Make loki work with Storybook8

### LINKED ISSUE #503: Storybook 8 compatibility
Hey team! I’m reaching out from the core SB team :)

Storybook 8 (our next major release) is coming soon, and it introduces some breaking changes that your addon might need to account for.

We’ve listed all the key changes in [a new Storybook 8 migration guide](https://storybook.js.org/docs/8.0/addons/addon-migration-guide#key-changes-for-addons), and we’d encourage you to check it out and see if your addon is impacted.

We also have an addons channel in our Discord community, which we’d like to use to better communicate with addon authors in the future. If you’re not part of the server, consider joining [here](https://discord.gg/wMff8FkF) and message me (@joevaugh4n) so that I can give you the addon creator role! If you’re already in the server, please just ping me and I’ll respond to you there.

Thanks for being a part of our addon community!

Joe

### PR DESCRIPTION
**Pull request by Benrajalu**
This PR enables loki on Storybook 8. 

It only fixes the API calls required but doesn't challenge the core concepts which rely on `storyStore.raw()`. That is still deprecated and will be gone for Storybook 9.

fixes #503

### CODE REVIEW

File: packages/browser/src/get-stories.js [hunk 1]
```diff
@@ -3,6 +3,7 @@
 const getStories = async (window) => {
   const getStorybook =
     (window.__STORYBOOK_CLIENT_API__ && window.__STORYBOOK_CLIENT_API__.raw) ||
+    (window.__STORYBOOK_PREVIEW__ && window.__STORYBOOK_PREVIEW__.extract && window.__STORYBOOK_PREVIEW__.storyStore.raw) ||
```
Comment (oblador) [inline packages/browser/src/get-stories.js:6]:
```suggestion
    (window.__STORYBOOK_PREVIEW__ &&
      window.__STORYBOOK_PREVIEW__.extract &&
      window.__STORYBOOK_PREVIEW__.storyStore.raw) ||
```
